[phases.setup]
nixPkgs = ["...", "php84Extensions.pgsql", "php84Extensions.pdo_pgsql"]

[phases.build]
cmds = [
    "npm ci",
    "npm run build",
    "composer install --no-dev --optimize-autoloader",
    "php artisan view:cache",
]

[start]
cmd = "php artisan config:clear && php artisan config:cache && php artisan route:cache && php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
